### ISSUE TITLE
Add .gitignore to your repo

### ISSUE THREAD

**Issue by abruzzihraig** [HeyDaniyar/SimpleToDo#1]
Dude, I think you'd better add a file named .gitignore to ignore the 3rd-party libraries in your repo.

**Comment by HeyDaniyar** [comment]
I have .gitignore file in my local repo, but seems that it was not uploaded

**Comment by abruzzihraig** [comment]
I mean you should ignore the files located public/lib.

**Comment by HeyDaniyar** [comment]
Got U, thanks  😘
