### ISSUE TITLE
Nothing shows when running it 

### ISSUE THREAD

**Issue by dilyar85** [HeyDaniyar/SimpleToDo#2]
So I followed your instructions and tried to run this application on my browser. However, I found nothing but a blank page on the http://localhost:8080. 
![image](https://cloud.githubusercontent.com/assets/10840560/19457072/74a4378c-9479-11e6-9609-0992e6332103.png)

**Comment by HeyDaniyar** [comment]
You need to run  "bower install "  in the public folder to install the necessary components.  I have modified the readme. Thanks bro
